- hosts: FTDOS
  connection: httpapi
  tasks:
    - name: Install image v6.4.0 on FTD 2110
      ftd_install:
        device_hostname: admin
        device_password: Passw0rd!

        console_ip: 10.44.22.1
        console_port: 2026
        console_username: root
        console_password: default

        rommon_file_location: 'tftp://10.89.0.11/installers/fxos-k8-fp2k-lfbff.2.6.1.94i.SPA'
        image_file_location: 'tftp://10.89.0.11/installers/cisco-ftd-fp2k.6.4.0-1293.SPA'
        image_version: 6.4.0-1292
