- hosts: web
  become: yes
  vars:
    your_impression: awesome
  tasks:
    - name: install package
      yum:
        name: httpd
        state: latest

    - name: put template file
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes
