- hosts: web
  become: yes
  vars:
    your_impression: awesome
  tasks:
    - name: install package
      yum:
        name: httpd
        state: latest

    - name: put template file
      template:
        src: /root/ansiblefiles/webserver_create/index.html.j2
        dest: /var/www/html/index.html
        owner=root
        group=root
        mode=0644

    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes
